Repository outpost-os/outpost-devicetree, pull requests merged in 2025-01, with the labels that each got.

#8 Remove dunamai for dynamic versioning
  meson.build
  support/meson/version.sh
Labels: enhancement

#9 st,wb: add syscfg device node
  dts/manufacturer/st/wb/stm32wb.dtsi
Labels: feature

#5 h7: fixing dtsi to stay generic, removing zephyr-related
  dts/manufacturer/st/h7/stm32h7.dtsi
  dts/manufacturer/st/h7/stm32h743.dtsi
  include/dt-bindings/memory-attr/memory-attr-arm.h
  include/dt-bindings/memory-attr/memory-attr.h
Labels: bug
